### ISSUE TITLE
Training freezes with 100% GPU utilization

### ISSUE THREAD

**Issue by BatyrbekSM** [chenyilun95/DSGN2#20]
When using the provided training script on 4 RTX 3090 GPUs, the training freezes or hangs with 100% GPU Utilization. Strangely, it happens randomly but anyway, you should always check training because it can stop in the middle of training.

**Comment by chenyilun95** [comment]
That's strange. I'm not sure if it's due to the GPU types. It should work when trained with 8 V100 GPUs (32GB each). If the training hangs, you might try continuing the training process.

**Comment by BatyrbekSM** [comment]
Yes, that is what I am doing each time, but the training takes 15-16 hours, so if it stucks at the initial phases of training (a first couple of epochs), you can lose time not knowing the training was stuck. Can it be due to PyTorch version? I am using the version 1.8.0-cu111 so that it can work in CUDA drivers 12.2, thus I have a little bit different envrionment setting.

**Comment by BatyrbekSM** [comment]
I found the solution to the problem but I am not sure whether this solution is permanent, at least for my current run it did not freeze at all: use `export NCCL_P2P_DISABLE=1` to make peer-to-peer communication in shared memory, I found out that the freezing problem might be due to deadlock during GPU communications.
